name: "Install linux dependencies"

runs:
  using: "composite"
  steps:
    - uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: 'mpv-player'
        repository: 'mpv-build'
    - uses: ConorMacBride/install-package@v1
      with:
        apt: libatk1.0-0 libgtk-3-dev libmpv-dev